allow = ["cargo"]
warn = []
forbid = ["complexity", "style", "nursery", "pedantic", "suspicious", "correctness", "perf"]
before-cargo = ["cargo fmt","cargo update"]
cargo = ["verify-project", "check --all-targets --profile=test", "audit", "test -j 4 --no-fail-fast -- --show-output", "fmt --check", "outdated"]
after-cargo = []
